DECLARE @AppCode NVARCHAR(10) = 'RUBIX-X',
		@CreateDate DATETIME = '2023-08-30'

INSERT INTO [dbo].[tb_Application] VALUES (@AppCode, 'RUBIX-X Framework', 1, @CreateDate, 1)
INSERT INTO [dbo].[tb_Permission] VALUES ('OPN', 'Open', 1, 1, @CreateDate, 1, @CreateDate, 1)
INSERT INTO [dbo].[tb_Permission] VALUES ('ADD', 'Add', 2, 1, @CreateDate, 1, @CreateDate, 1)
INSERT INTO [dbo].[tb_Permission] VALUES ('EDT', 'Edit', 3, 1, @CreateDate, 1, @CreateDate, 1)
INSERT INTO [dbo].[tb_Permission] VALUES ('DEL', 'Delete', 4, 1, @CreateDate, 1, @CreateDate, 1)
INSERT INTO [dbo].[tb_PermissionName] VALUES ('OPN', 'en-US', 'Open')
INSERT INTO [dbo].[tb_PermissionName] VALUES ('ADD', 'en-US', 'Add')
INSERT INTO [dbo].[tb_PermissionName] VALUES ('EDT', 'en-US', 'Edit')
INSERT INTO [dbo].[tb_PermissionName] VALUES ('DEL', 'en-US', 'Delete')
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS020', N'home', N'/s/home', 1, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS030', N'person_add', N'/s/auth/usr/s', 2, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS031', N'person_add', N'/s/auth/usr/d', 3, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS040', N'group_add', N'/s/auth/grp/s', 4, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS041', N'group_add', N'/s/auth/grp/d', 5, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS050', N'folder_managed', N'/s/auth/p/s', 6, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS051', N'folder_managed', N'/s/auth/p/d', 7, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS060', N'web_asset', N'/s/auth/s/s', 8, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS061', N'web_asset', N'/s/auth/s/d', 9, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS070', N'list', N'/s/auth/m/s', 10, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_Screen] VALUES (@AppCode, N'SSS071', N'list', N'/s/auth/m/d', 11, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS020', N'en-US', N'Dashboard')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS030', N'en-US', N'User Profile')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS031', N'en-US', N'User Profile Detail')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS040', N'en-US', N'User Group')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS041', N'en-US', N'User Group Detail')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS050', N'en-US', N'Permission')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS051', N'en-US', N'Permission Detail')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS060', N'en-US', N'Screen')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS061', N'en-US', N'Screen Detail')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS070', N'en-US', N'Menu')
INSERT [dbo].[tb_ScreenName] VALUES (@AppCode, N'SSS071', N'en-US', N'Menu Detail')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS031', N'ADD')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS041', N'ADD')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS051', N'ADD')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS061', N'ADD')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS071', N'ADD')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS031', N'DEL')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS041', N'DEL')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS051', N'DEL')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS061', N'DEL')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS071', N'DEL')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS031', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS041', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS050', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS051', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS060', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS061', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS070', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS071', N'EDT')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS020', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS030', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS031', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS040', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS041', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS050', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS051', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS060', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS061', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS070', N'OPN')
INSERT [dbo].[tb_ScreenPermission] VALUES (@AppCode, N'SSS071', N'OPN')
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 1, N'G', NULL, 1, N'home', NULL, NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 2, N'I', 1, 1, NULL, N'SSS020', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 3, N'G', NULL, 2, N'manage_accounts', NULL, NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 4, N'I', 3, 2, NULL, N'SSS030', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 5, N'I', 3, 1, NULL, N'SSS040', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 6, N'G', 3, 3, N'settings', NULL, NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 7, N'I', 6, 1, NULL, N'SSS050', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 8, N'I', 6, 2, NULL, N'SSS060', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuSetting] VALUES (@AppCode, 9, N'I', 6, 3, NULL, N'SSS070', NULL, 1, @CreateDate, 1, @CreateDate, 1)
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 1, N'en-US', N'Home')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 2, N'en-US', N'Dashboard')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 3, N'en-US', N'Administration')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 4, N'en-US', N'User Profile')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 5, N'en-US', N'User Group')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 6, N'en-US', N'Setting')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 7, N'en-US', N'Permission')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 8, N'en-US', N'Screen')
INSERT [dbo].[tb_MenuName] VALUES (@AppCode, 9, N'en-US', N'Menu')