// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicationPostgreSQLDB.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206184352_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActiveDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("FirstLoginFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InActiveDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("LastUpdatePasswordDate")
                        .HasColumnType("DATE");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("PasswordAge")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("SystemAdminFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("tb_User", "public");
                });

            modelBuilder.Entity("Application.Models.tb_PasswordHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(450)")
                        .HasComment("User ID (Main Key)");

                    b.Property<int>("HistoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HistoryDate")
                        .HasColumnType("DATE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id", "HistoryId");

                    b.ToTable("tb_PasswordHistory", "public");
                });

            modelBuilder.Entity("Application.Models.tb_UserInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR(450)")
                        .HasComment("User ID (Main Key)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("integer")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATE")
                        .HasComment("Create Date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasComment("First Name");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("VARCHAR")
                        .HasComment("Language Code login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasComment("Last Name");

                    b.Property<string>("Remark")
                        .HasColumnType("VARCHAR")
                        .HasComment("Remark, more note.");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("integer")
                        .HasComment("Update By");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATE")
                        .HasComment("Update Date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasComment("UserName");

                    b.Property<int>("UserNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tb_UserInfo", "public");
                });

            modelBuilder.Entity("Application.Models.tb_UserLogTrail", b =>
                {
                    b.Property<string>("action_name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasComment("Action Name");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("DATE")
                        .HasComment("Create Date");

                    b.Property<string>("create_user")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasComment("Create User");

                    b.Property<string>("data_after")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasComment("Data After");

                    b.Property<string>("data_before")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)")
                        .HasComment("Data Before");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasComment("UserID");

                    b.ToTable("tb_userlogtrail", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("tb_Role", "public");

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_RoleClaim", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tb_UserClaim", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tb_UserLogin", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_UserRole", "public");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tb_UserToken", "public");
                });

            modelBuilder.Entity("Application.Models.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("integer")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATE")
                        .HasComment("Create Date");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(256)");

                    b.Property<bool>("SystemAdminFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("integer")
                        .HasComment("Update By");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATE")
                        .HasComment("Update Date");

                    b.ToTable("tb_Role", "public");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("Application.Models.tb_PasswordHistory", b =>
                {
                    b.HasOne("Application.Models.ApplicationUser", "User")
                        .WithMany("PasswordHistories")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Application.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Application.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Application.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Application.Models.ApplicationUser", b =>
                {
                    b.Navigation("PasswordHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
