// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations.System
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.tb_Application", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Create Date");

                    b.HasKey("AppCode");

                    b.ToTable("tb_Application", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_MenuName", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasComment("Running Unique Record Id");

                    b.Property<string>("Language")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Language Code such as en-US, th-TH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasComment("Menu Name of Language");

                    b.HasKey("AppCode", "MenuId", "Language");

                    b.ToTable("tb_MenuName", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_MenuSetting", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasComment("Running Unique Record Id");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Create Date");

                    b.Property<string>("ImageIcon")
                        .HasColumnType("NVARCHAR(50)")
                        .HasComment("Screen Icon Name");

                    b.Property<string>("MenuType")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasComment("G = Group Folder, I = Item");

                    b.Property<string>("MenuURL")
                        .HasColumnType("NVARCHAR(255)")
                        .HasComment("Link");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int")
                        .HasComment("Parent Menu Id");

                    b.Property<string>("ScreenId")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Screen Id");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int")
                        .HasComment("Sequence No. (Re-Order every updating)");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int")
                        .HasComment("Update By");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Update Date");

                    b.HasKey("AppCode", "MenuId");

                    b.HasIndex("AppCode", "ScreenId");

                    b.ToTable("tb_MenuSetting", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_Permission", b =>
                {
                    b.Property<string>("PermissionCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Permission Code");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Create Date");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(MAX)")
                        .HasComment("Permission Description");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int")
                        .HasComment("Sequence No. for sorting display list.");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int")
                        .HasComment("Update By");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Update Date");

                    b.HasKey("PermissionCode");

                    b.ToTable("tb_Permission", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_PermissionName", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Permission Code");

                    b.Property<string>("Language")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Language Code such as en-US, th-TH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasComment("Screen Name of Language");

                    b.HasKey("PermissionCode", "Language");

                    b.ToTable("tb_PermissionName", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_Screen", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("ScreenId")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Screen Id");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int")
                        .HasComment("Create By");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Create Date");

                    b.Property<string>("ImageIcon")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasComment("Screen Icon Name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasComment("Screen Path");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int")
                        .HasComment("Sequence No. for sorting display list.");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int")
                        .HasComment("Update By");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("DATETIME")
                        .HasComment("Update Date");

                    b.HasKey("AppCode", "ScreenId");

                    b.ToTable("tb_Screen", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_ScreenName", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("ScreenId")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Screen Id");

                    b.Property<string>("Language")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Language Code such as en-US, th-TH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasComment("Menu Name of Language");

                    b.HasKey("AppCode", "ScreenId", "Language");

                    b.ToTable("tb_ScreenName", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_ScreenPermission", b =>
                {
                    b.Property<string>("AppCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<string>("ScreenId")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Screen Id");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("NVARCHAR(10)")
                        .HasComment("Permission Code");

                    b.HasKey("AppCode", "ScreenId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("tb_ScreenPermission", "dbo");
                });

            modelBuilder.Entity("Application.Models.tb_MenuName", b =>
                {
                    b.HasOne("Application.Models.tb_MenuSetting", "MenuSetting")
                        .WithMany("MenuNames")
                        .HasForeignKey("AppCode", "MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuSetting");
                });

            modelBuilder.Entity("Application.Models.tb_MenuSetting", b =>
                {
                    b.HasOne("Application.Models.tb_Screen", "Screen")
                        .WithMany("MenuSettings")
                        .HasForeignKey("AppCode", "ScreenId");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Application.Models.tb_PermissionName", b =>
                {
                    b.HasOne("Application.Models.tb_Permission", "Permission")
                        .WithMany("PermissionNames")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Application.Models.tb_ScreenName", b =>
                {
                    b.HasOne("Application.Models.tb_Screen", "Screen")
                        .WithMany("ScreenNames")
                        .HasForeignKey("AppCode", "ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Application.Models.tb_ScreenPermission", b =>
                {
                    b.HasOne("Application.Models.tb_Permission", "Permission")
                        .WithMany("ScreenPermissions")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Models.tb_Screen", "Screen")
                        .WithMany("ScreenPermissions")
                        .HasForeignKey("AppCode", "ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("Application.Models.tb_MenuSetting", b =>
                {
                    b.Navigation("MenuNames");
                });

            modelBuilder.Entity("Application.Models.tb_Permission", b =>
                {
                    b.Navigation("PermissionNames");

                    b.Navigation("ScreenPermissions");
                });

            modelBuilder.Entity("Application.Models.tb_Screen", b =>
                {
                    b.Navigation("MenuSettings");

                    b.Navigation("ScreenNames");

                    b.Navigation("ScreenPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
